[package]
name = "tauri-plugin-aptabase"
version = "0.3.0"
license = "MIT"
description = "Tauri Plugin for Aptabase: Open Source, Privacy-First and Simple Analytics for Mobile, Desktop and Web Apps"
authors = [ "Guilherme Oenning" ]
edition = "2021"
rust-version = "1.59"
readme = "README.md"
repository = "https://github.com/aptabase/tauri-plugin-aptabase"
exclude = ["/examples", "/webview-dist", "/webview-src", "node_modules"]

[dependencies]
tauri = "1"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
reqwest = { version = "0.11", features = ["json"] }
time = { version = "0.3", features = ["formatting"]}
os_info = "3"
sys-locale = "0.3"
uuid = "1"
wry = "0"
log = "0.4"
